Lab1
beekebak/osi pull request #2
Opened 2024-04-09 13:40 UTC by beekebak

2024-04-12 17:21 UTC, ksilobait requested changes

2024-04-12 17:21 UTC, ksilobait commented on lab1/lab1_1/hello
Бинарные файлы не нужно коммитить в репозиторий

2024-04-12 17:21 UTC, ksilobait commented on lab1/lab1_3/readme.md
Не хватает команды где операционной системе искать библиотеку вроде
export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH

2024-04-12 17:21 UTC, ksilobait commented on lab1/lab1_4/hello.c
> +  dlclose(handle);
dlclose тоже может вернуть ошибку
Все системные вызовы, которые могут вернуть ошибку, нужно проверить и сообщить пользователю

2024-05-09 03:20 UTC, beekebak commented on lab1/lab1_3/readme.md
у меня это вроде во флагах компиляции было, добавил вместо них переменную окружения

2024-05-09 03:20 UTC, beekebak commented on lab1/lab1_4/hello.c
> +  dlclose(handle);
добавил проверку

2024-05-10 13:22 UTC, merged